In [1]:
import pandas as pd
import numpy as np
pd.options.plotting.backend = "plotly"

X_train = pd.read_csv('data/X_train.csv', sep = ',', index_col=0)
X_test = pd.read_csv('data/X_test.csv', sep = ',', index_col=0)
cols_to_drop = ["CNTSTUID", "CYC"] + ['math_q21_total_timing', 'math_q19_total_timing', 'math_q20_total_timing', 'math_q17_total_timing', 'math_q18_total_timing', 'math_q14_total_timing', 'math_q13_total_timing', 'math_q16_total_timing', 'math_q15_total_timing', 'math_q12_total_timing', 'math_q11_total_timing', 'math_q9_total_timing', 'math_q10_total_timing', 'math_q2_total_timing', 'math_q5_total_timing', 'math_q8_total_timing', 'math_q7_total_timing', 'math_q6_total_timing', 'math_q3_total_timing', 'math_q4_total_timing', 'math_q11_average_score', 'math_q10_average_score', 'math_q9_average_score', 'math_q8_average_score', 'math_q7_average_score', 'math_q6_average_score', 'math_q5_average_score', 'math_q20_average_score', 'math_q19_average_score', 'math_q4_average_score', 'math_q3_average_score', 'math_q1_average_score', 'math_q2_average_score', 'math_q15_average_score', 'math_q16_average_score', 'math_q17_average_score', 'math_q18_average_score', 'math_q13_average_score', 'math_q12_average_score', 'math_q14_average_score', 'science_q18_total_timing', 'science_q16_average_score', 'science_q19_average_score', 'science_q18_average_score', 'science_q19_total_timing', 'science_q17_total_timing', 'science_q16_total_timing', 'science_q14_average_score', 'science_q15_average_score', 'reading_q15_average_score', 'science_q15_total_timing', 'science_q14_total_timing', 'science_q17_average_score', 'science_q13_average_score', 'math_q21_average_score', 'science_q13_total_timing', 'reading_q15_total_timing', 'reading_q14_average_score', 'reading_q14_total_timing', 'reading_q13_average_score', 'reading_q13_total_timing', 'reading_q12_average_score', 'reading_q11_average_score', 'reading_q12_total_timing', 'reading_q11_total_timing', 'reading_q10_average_score', 'reading_q10_total_timing', 'science_q12_total_timing', 'science_q12_average_score', 'reading_q9_average_score', 'reading_q9_total_timing']

In [2]:
X_train = X_train.drop(columns=cols_to_drop)
exo_embedding_finetuned_full_train = pd.read_csv("data/Embedding_wandb/exo_embedding_finetuned_full_train.csv",index_col=0)
que_embedding_finetuned_full_train = pd.read_csv("data/Embedding_wandb/que_embedding_finetuned_full_train.csv",index_col=0)
df_preprocessed = pd.read_csv("data/df_processed.csv",index_col=0)
mask = df_preprocessed["MathScore"].notna()
df_preprocessed= df_preprocessed.loc[mask]

X_train = X_train.join(exo_embedding_finetuned_full_train, how='left')
X_train = X_train.join(que_embedding_finetuned_full_train, how='left')

# X_train["STRATUM_CLUST"] =df_preprocessed["STRATUM"]
# X_train["DIFFERENT"] =df_preprocessed["DIFFERENT"]
# X_train["OCOD1_ISEI"] =df_preprocessed["OCOD1"]
# X_train["OCOD2_ISEI"] =df_preprocessed["OCOD2"]
# X_train["OCOD3_ISEI"] =df_preprocessed["OCOD3"]
# X_train["IND_ST001D01T"] =df_preprocessed["ST001D01T"]

In [3]:
X_train["MathScore"] = df_preprocessed["MathScore"]

In [4]:
import pandas as pd
from autogluon.tabular import TabularDataset, TabularPredictor

train_data = TabularDataset(X_train)
train_data.head()

/root/autogluon-gpu/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,Year,CNT,CNTRYID,CNTSCHID,NatCen,STRATUM,SUBNATIO,OECD,ADMINMODE,LANGTEST_QQQ,...,QUE_EMBD_56,QUE_EMBD_57,QUE_EMBD_58,QUE_EMBD_59,QUE_EMBD_60,QUE_EMBD_61,QUE_EMBD_62,QUE_EMBD_63,QUE_EMBD_64,MathScore
384002,2022,NLD,528.0,52800132.0,52800,NLD06,5280000,1.0,2.0,322.0,...,2.844303,1.646708,0.409935,0.589777,1.572640,2.357127,2.817733,3.115617,1.985909,116.975422
1118072,2018,QAZ,31.0,3100106.0,3100,QAZ0101,310000,0.0,2.0,803.0,...,1.176104,1.177561,-0.117743,-0.123372,-0.155944,0.367609,0.771660,-0.162681,1.088502,73.387560
845454,2018,FRA,250.0,25000010.0,25000,FRA0101,2500000,1.0,2.0,493.0,...,2.695538,1.136000,3.418716,3.104094,0.399592,1.690193,2.961795,2.567556,0.718764,0.000000
1728613,2015,QES,971.0,97100240.0,72400,ESP1633,7241600,2.0,2.0,156.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
1083243,2018,PHL,608.0,60800071.0,60800,PHL0011,6080000,0.0,2.0,313.0,...,2.645213,2.330520,-0.000661,-0.003746,0.373032,0.185785,0.062596,-0.032315,1.986596,113.750718

In [5]:
label = 'MathScore'
time_limit = 105*60
metric = 'r2'
predictor = TabularPredictor(label, eval_metric=metric).fit(train_data,
                                                            time_limit=time_limit,
                                                              presets='extreme_quality', num_gpus=1,
                                                              dynamic_stacking=False, num_stack_levels=1,
                                                              excluded_model_types=['RF'])

No path specified. Models will be saved in: "AutogluonModels/ag-20251130_123011"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.12.3
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #85-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep 18 15:26:59 UTC 2025
CPU Count:          24
Memory Avail:       136.03 GB / 235.94 GB (57.7%)
Disk Space Avail:   63.77 GB / 111.72 GB (57.1%)
===================================================
Presets specified: ['extreme_quality']
`extreme` preset uses a dynamic portfolio based on dataset size...
	Detected data size: large (>30000 samples), using `zeroshot` portfolio (identical to 'best_quality' preset).
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Beginning AutoGluon training ... Time limit = 6300s
AutoGluon will save models to "/root/AutogluonModels/ag-20251130_123011"
Train Data Rows:    1172086
Train Data Columns: 361
Label Column:       MathScore
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (814.972459371057, 0.0, 99.99513, 122.17608)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    139157.49 MB
	Train Data (Original)  Memory Usage: 3330.22 MB (2.4% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 356 | ['CNTRYID', 'CNTSCHID', 'OECD', 'ADMINMODE', 'LANGTEST_QQQ', ...]
		('int', [])    :   3 | ['Year', 'NatCen', 'SUBNATIO']
		('object', []) :   2 | ['CNT', 'STRATUM']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :   2 | ['CNT', 'STRATUM']
		('float', [])     : 355 | ['CNTRYID', 'CNTSCHID', 'OECD', 'LANGTEST_QQQ', 'LANGTEST_COG', ...]
		('int', [])       :   3 | ['Year', 'NatCen', 'SUBNATIO']
		('int', ['bool']) :   1 | ['ADMINMODE']
	16.4s = Fit runtime
	361 features in original data used to generate 361 features in processed data.
	Train Data (Processed) Memory Usage: 3205.82 MB (2.3% of available memory)
Data preprocessing and feature engineering runtime = 18.05s ...
AutoGluon will gauge predictive performance using evaluation metric: 'r2'
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Excluded models: ['RF'] (Specified by `excluded_model_types`)
Fitting 98 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 4186.92s of the 6281.95s of remaining time.
2025-11-30 12:30:40,403	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
	Memory not enough to fit 8 folds in parallel. Will train 4 folds in parallel instead (Estimated 14.95% memory usage per fold, 59.78%/80.00% total).
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=6, gpus=0, memory=14.95%)
	0.7838	 = Validation score   (r2)
	2908.57s	 = Training   runtime
	112.19s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 1251.33s of the 3346.36s of remaining time.
	Memory not enough to fit 8 folds in parallel. Will train 4 folds in parallel instead (Estimated 11.65% memory usage per fold, 46.61%/80.00% total).
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=6, gpus=0, memory=11.65%)
	0.7769	 = Validation score   (r2)
	878.59s	 = Training   runtime
	28.95s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 356.66s of the 2451.68s of remaining time.
	Memory not enough to fit 8 folds in parallel. Will train 4 folds in parallel instead (Estimated 12.01% memory usage per fold, 48.05%/80.00% total).
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2.0 workers, per: cpus=12, gpus=0, memory=12.01%)
	0.7677	 = Validation score   (r2)
	282.0s	 = Training   runtime
	0.68s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 61.95s of the 2156.98s of remaining time.
	Not enough time to generate out-of-fold predictions for model. Estimated time required was 115.21s compared to 10s of available time.
	Time limit exceeded... Skipping ExtraTreesMSE_BAG_L1.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 418.69s of the 1645.87s of remaining time.
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.812, 'LightGBM_BAG_L1': 0.125, 'CatBoost_BAG_L1': 0.062}
	0.7842	 = Validation score   (r2)
	0.37s	 = Training   runtime
	0.01s	 = Validation runtime
Excluded models: ['RF'] (Specified by `excluded_model_types`)
Fitting 98 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 1645.46s of the 1645.11s of remaining time.
	Memory not enough to fit 8 folds in parallel. Will train 4 folds in parallel instead (Estimated 12.43% memory usage per fold, 49.73%/80.00% total).
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=6, gpus=0, memory=12.43%)
	0.7839	 = Validation score   (r2)
	274.87s	 = Training   runtime
	5.22s	 = Validation runtime
Fitting model: LightGBM_BAG_L2 ... Training model for up to 1356.87s of the 1356.52s of remaining time.
	Memory not enough to fit 8 folds in parallel. Will train 4 folds in parallel instead (Estimated 12.14% memory usage per fold, 48.55%/80.00% total).
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=6, gpus=0, memory=12.14%)
	0.7831	 = Validation score   (r2)
	83.9s	 = Training   runtime
	1.21s	 = Validation runtime
Fitting model: CatBoost_BAG_L2 ... Training model for up to 1260.12s of the 1259.77s of remaining time.
	Memory not enough to fit 8 folds in parallel. Will train 4 folds in parallel instead (Estimated 12.64% memory usage per fold, 50.58%/80.00% total).
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2.0 workers, per: cpus=12, gpus=0, memory=12.64%)
	0.7862	 = Validation score   (r2)
	1004.71s	 = Training   runtime
	0.78s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L2 ... Training model for up to 242.61s of the 242.26s of remaining time.
	Not enough time to generate out-of-fold predictions for model. Estimated time required was 114.42s compared to 23.68s of available time.
	Time limit exceeded... Skipping ExtraTreesMSE_BAG_L2.
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the -208.35s of remaining time.
	Ensemble Weights: {'CatBoost_BAG_L2': 0.933, 'LightGBMXT_BAG_L2': 0.067}
	0.7862	 = Validation score   (r2)
	0.64s	 = Training   runtime
	0.01s	 = Validation runtime
AutoGluon training complete, total runtime = 6513.36s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 991.1 rows/s (146511 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/root/AutogluonModels/ag-20251130_123011")

In [6]:
X_test = X_test.drop(columns=cols_to_drop)
exo_embedding_finetuned_full_test = pd.read_csv("data/Embedding_wandb/exo_embedding_finetuned_full_test.csv",index_col=0)
que_embedding_finetuned_full_test = pd.read_csv("data/Embedding_wandb/que_embedding_finetuned_full_test.csv",index_col=0)
df_preprocessed_test = pd.read_csv("data/df_processed.csv",index_col=0)
mask_test = df_preprocessed_test["MathScore"].isna()
df_preprocessed_test= df_preprocessed_test.loc[mask_test]

X_test = X_test.join(exo_embedding_finetuned_full_test, how='left')
X_test = X_test.join(que_embedding_finetuned_full_test, how='left')

# X_test["STRATUM_CLUST"] =df_preprocessed_test["STRATUM"]
# X_test["DIFFERENT"] =df_preprocessed_test["DIFFERENT"]
# X_test["OCOD1_ISEI"] =df_preprocessed_test["OCOD1"]
# X_test["OCOD2_ISEI"] =df_preprocessed_test["OCOD2"]
# X_test["OCOD3_ISEI"] =df_preprocessed_test["OCOD3"]
# X_test["IND_ST001D01T"] =df_preprocessed_test["ST001D01T"]

In [7]:
test_data = TabularDataset(X_test)
test_data.head()

,Year,CNT,CNTRYID,CNTSCHID,NatCen,STRATUM,SUBNATIO,OECD,ADMINMODE,LANGTEST_QQQ,...,QUE_EMBD_55,QUE_EMBD_56,QUE_EMBD_57,QUE_EMBD_58,QUE_EMBD_59,QUE_EMBD_60,QUE_EMBD_61,QUE_EMBD_62,QUE_EMBD_63,QUE_EMBD_64
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
412660,2022,PER,604.0,60400217.0,60400,PER03,6040000,0.0,2.0,156.0,...,1.670140,3.182690,1.073910,1.688801,0.155785,1.259226,1.758171,2.480654,1.911667,0.705660
554658,2022,ARE,784.0,78400570.0,78401,ARE41,7840000,0.0,2.0,500.0,...,-0.117289,-0.098046,0.688840,-0.149113,0.153654,-0.136456,1.590246,0.641020,-0.037355,1.751096
937138,2018,JOR,400.0,40000074.0,40000,JOR9797,4000000,0.0,1.0,500.0,...,1.670528,2.823090,1.725252,0.363153,1.122494,0.116005,1.794799,2.216852,2.055782,0.595472
752986,2018,CHL,152.0,15200099.0,15200,CHL0203,1520000,1.0,2.0,156.0,...,3.176360,1.502818,3.259160,0.240214,1.623496,2.137157,0.559613,2.439878,0.609418,2.213249
1084508,2018,PHL,608.0,60800098.0,60800,PHL0002,6080000,0.0,2.0,313.0,...,0.952266,2.211158,1.187473,-0.002283,0.089747,1.204264,0.584549,0.361273,0.317313,0.660442

In [8]:
y_pred = predictor.predict(test_data)
y_pred.head()

Unnamed: 0
412660     134.201141
554658      84.894302
937138       0.202696
752986     245.096191
1084508    113.735641
Name: MathScore, dtype: float32

In [9]:
y_pred = y_pred.clip(lower=0, upper=900)

In [10]:
y_pred.index.name = 'ID'
y_pred.head()

ID
412660     134.201141
554658      84.894302
937138       0.202696
752986     245.096191
1084508    113.735641
Name: MathScore, dtype: float32

In [11]:
y_pred.to_csv("data/autogluon_clipping.csv", index=True)