In [1]:
import pandas as pd

X_train = pd.read_csv('X_train.csv', sep = ',', index_col=0)
X_test = pd.read_csv('X_test.csv', sep = ',', index_col=0)

for c in ['PA008', 'ST006', 'ST008']:
    X_train[c] = X_train[c].fillna(X_train[f"{c}.1"])
    X_test[c] = X_test[c].fillna(X_train[f"{c}.1"])

X_train.drop(columns=['PA008.1', 'ST006.1', 'ST008.1'], inplace=True)
X_test.drop(columns=['PA008.1', 'ST006.1', 'ST008.1'], inplace=True)

X_train.to_csv("X_train.csv")
X_test.to_csv("X_test.csv")

#X_train["D_INDEX"] = X_train["CNTSTUID"].astype(str) + "/" + X_train["Year"].astype(str)

In [2]:
# 1) nb de tentatives par (étudiant, année)
attempts = X_train.groupby(["CNTSTUID", "Year"]).size()

# 2) cumsum par étudiant
cum = attempts.groupby(level=0).cumsum()

# 3) TIME = tentatives avant cette année + 1
time_per_year = (cum - attempts + 1).rename("TIME")

# 4) join sur les colonnes CNTSTUID, Year
X_train = X_train.join(time_per_year, on=["CNTSTUID", "Year"])

In [3]:
X_train["TIME"].value_counts().sort_index()

TIME
1    771247
2    323773
3     75763
4      1148
5       149
6         6
Name: count, dtype: int64

In [4]:
X_train["CNTSCHID"].unique()

array([52800132.,  3100106., 25000010., ..., 22200159., 48400174.,
       78800066.], shape=(28078,))

In [5]:
X_train["CYC"].apply(lambda s: s[0:2]).unique()

array(['08', '07', '06'], dtype=object)

In [6]:
columns_dae_piza = [
    # Reading average scores
    'reading_q1_average_score', 'reading_q2_average_score', 'reading_q3_average_score',
    'reading_q4_average_score', 'reading_q5_average_score', 'reading_q6_average_score',
    'reading_q7_average_score', 'reading_q8_average_score', 'reading_q9_average_score',
    'reading_q10_average_score', 'reading_q11_average_score', 'reading_q12_average_score',
    'reading_q13_average_score', 'reading_q14_average_score', 'reading_q15_average_score',
    # Math average scores
    'math_q1_average_score', 'math_q2_average_score', 'math_q3_average_score',
    'math_q4_average_score', 'math_q5_average_score', 'math_q6_average_score',
    'math_q7_average_score', 'math_q8_average_score', 'math_q9_average_score',
    'math_q10_average_score', 'math_q11_average_score', 'math_q12_average_score',
    'math_q13_average_score', 'math_q14_average_score', 'math_q15_average_score',
    'math_q16_average_score', 'math_q17_average_score', 'math_q18_average_score',
    'math_q19_average_score', 'math_q20_average_score', 'math_q21_average_score',
    # Science average scores
    'science_q1_average_score', 'science_q2_average_score', 'science_q3_average_score',
    'science_q4_average_score', 'science_q5_average_score', 'science_q6_average_score',
    'science_q7_average_score', 'science_q8_average_score', 'science_q9_average_score',
    'science_q10_average_score', 'science_q11_average_score', 'science_q12_average_score',
    'science_q13_average_score', 'science_q14_average_score', 'science_q15_average_score',
    'science_q16_average_score', 'science_q17_average_score', 'science_q18_average_score',
    'science_q19_average_score',
    # Reading total timing
    'reading_q1_total_timing', 'reading_q2_total_timing', 'reading_q3_total_timing',
    'reading_q4_total_timing', 'reading_q5_total_timing', 'reading_q6_total_timing',
    'reading_q7_total_timing', 'reading_q8_total_timing', 'reading_q9_total_timing',
    'reading_q10_total_timing', 'reading_q11_total_timing', 'reading_q12_total_timing',
    'reading_q13_total_timing', 'reading_q14_total_timing', 'reading_q15_total_timing',
    # Math total timing
    'math_q1_total_timing', 'math_q2_total_timing', 'math_q3_total_timing',
    'math_q4_total_timing', 'math_q5_total_timing', 'math_q6_total_timing',
    'math_q7_total_timing', 'math_q8_total_timing', 'math_q9_total_timing',
    'math_q10_total_timing', 'math_q11_total_timing', 'math_q12_total_timing',
    'math_q13_total_timing', 'math_q14_total_timing', 'math_q15_total_timing',
    'math_q16_total_timing', 'math_q17_total_timing', 'math_q18_total_timing',
    'math_q19_total_timing', 'math_q20_total_timing', 'math_q21_total_timing',
    # Science total timing
    'science_q1_total_timing', 'science_q2_total_timing', 'science_q3_total_timing',
    'science_q4_total_timing', 'science_q5_total_timing', 'science_q6_total_timing',
    'science_q7_total_timing', 'science_q8_total_timing', 'science_q9_total_timing',
    'science_q10_total_timing', 'science_q11_total_timing', 'science_q12_total_timing',
    'science_q13_total_timing', 'science_q14_total_timing', 'science_q15_total_timing',
    'science_q16_total_timing', 'science_q17_total_timing', 'science_q18_total_timing',
    'science_q19_total_timing'
]
X_train_piza = X_train[columns_dae_piza]

X_train_piza = X_train_piza[X_train_piza.isna().sum(axis=1) < 100]

In [ ]:
X_train_piza.isna().sum(axis=1).max()

In [18]:
data_raw = X_train_piza

In [19]:
data_raw

,reading_q1_average_score,reading_q2_average_score,reading_q3_average_score,reading_q4_average_score,reading_q5_average_score,reading_q6_average_score,reading_q7_average_score,reading_q8_average_score,reading_q9_average_score,reading_q10_average_score,...,science_q10_total_timing,science_q11_total_timing,science_q12_total_timing,science_q13_total_timing,science_q14_total_timing,science_q15_total_timing,science_q16_total_timing,science_q17_total_timing,science_q18_total_timing,science_q19_total_timing
384002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1118072,0.25,0.00,0.0,0.333333,0.466667,0.900000,0.00,0.90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
845454,0.75,1.00,0.0,0.500000,0.952381,0.333333,1.00,1.00,NaN,NaN,...,87686.500000,13164.75,1187.199951,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1728613,1.00,0.00,1.0,0.500000,1.000000,0.500000,1.00,1.00,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1083243,0.00,0.25,1.0,0.750000,0.000000,0.727273,0.50,0.50,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259178,0.25,1.00,0.0,0.400000,1.000000,0.500000,0.75,1.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1414414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45551.000000,82363.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131932,0.50,0.50,1.0,0.600000,0.866667,0.904762,0.75,1.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
671155,1.00,0.25,1.0,1.000000,1.000000,0.954545,0.50,0.75,1.0,NaN,...,66535.796875,43705.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121958,0.25,1.00,0.0,0.250000,0.681818,0.500000,0.50,1.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
import torch
from sklearn.preprocessing import RobustScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import KFold
import numpy as np

kfold = KFold(n_splits=5, shuffle=True, random_state=42)
for fold, (train_idx, val_idx) in enumerate(kfold.split(data_raw)):
    X_train_raw = data_raw.iloc[train_idx]
    X_val_raw = data_raw.iloc[val_idx]

    imputer = SimpleImputer(strategy="mean", keep_empty_features=True)
    X_train_imputed = imputer.fit_transform(X_train_raw)

    scaler = RobustScaler()
    X_train_scaled = scaler.fit_transform(X_train_imputed).astype(np.float32)

    if X_val_raw is not None:
        mask_val = (~np.isnan(X_val_raw)).astype(np.float32)
        X_val_imputed = imputer.transform(X_val_raw)
        X_val_scaled = scaler.transform(X_val_imputed).astype(np.float32)
    else:
        val_loader = None

    obs_train = X_train_scaled
    obs_val = X_val_scaled
    print("train |x| p50/p90/p99/max:", np.quantile(np.abs(obs_train), [0.5,0.9,0.99]), np.max(np.abs(obs_train)))
    print("val   |x| p50/p90/p99/max:", np.quantile(np.abs(obs_val), [0.5,0.9,0.99]), np.max(np.abs(obs_val)))

    print("scaler.scale_ min/p1/p5/median:", np.min(scaler.scale_), np.quantile(scaler.scale_, 0.01),
      np.quantile(scaler.scale_, 0.05), np.median(scaler.scale_))

    max_abs = np.max(np.abs(X_train_scaled), axis=0)
    n_obs = len(train_idx)
    df_dbg = pd.DataFrame({
        "col": columns_dae_piza,
        "max_abs": max_abs,
        "n_obs": n_obs,
        "scale": scaler.scale_,
    }).sort_values("max_abs", ascending=False)
    print(df_dbg.head(20))

train |x| p50/p90/p99/max: [0.00000000e+00 2.84455252e+00 2.57283535e+04] 3.186484e+07
val   |x| p50/p90/p99/max: [0.00000000e+00 2.83628514e+00 2.56563489e+04] 2.5147016e+07
scaler.scale_ min/p1/p5/median: 0.008107565643202586 0.02249734382190503 0.16666666666666666 1.0
                          col       max_abs   n_obs         scale
63    reading_q9_total_timing  3.186484e+07  923309      1.000000
101  science_q11_total_timing  2.476991e+07  923309      1.000000
80      math_q11_total_timing  1.522276e+07  923309      1.000000
100  science_q10_total_timing  1.200930e+07  923309      1.000000
99    science_q9_total_timing  1.091799e+07  923309      1.000000
62    reading_q8_total_timing  6.277936e+06  923309      1.000000
81      math_q12_total_timing  6.041690e+06  923309      1.000000
85      math_q16_total_timing  5.105610e+06  923309      1.000000
84      math_q15_total_timing  3.808200e+06  923309      1.000000
82      math_q13_total_timing  3.660971e+06  923309      1.000000
102  science_q12_total_timing  1.293505e+06  923309      1.000000
83      math_q14_total_timing  9.446810e+05  923309      1.000000
64   reading_q10_total_timing  2.427798e+05  923309      1.000000
65   reading_q11_total_timing  1.447122e+05  923309      1.000000
66   reading_q12_total_timing  1.392142e+05  923309      1.000000
68   reading_q14_total_timing  7.202473e+04  923309      1.000000
67   reading_q13_total_timing  6.081548e+04  923309      1.000000
61    reading_q7_total_timing  1.243661e+04  923309   1113.108052
69   reading_q15_total_timing  1.136100e+04  923309      1.000000
78       math_q9_total_timing  4.891803e+03  923309  15409.368909
train |x| p50/p90/p99/max: [0.00000000e+00 2.84708550e+00 2.57187624e+04] 2.5146884e+07
val   |x| p50/p90/p99/max: [0.00000000e+00 2.83899231e+00 2.56983994e+04] 3.186529e+07
scaler.scale_ min/p1/p5/median: 0.008041332642302224 0.022551012496797113 0.16666666666666666 1.0
                          col       max_abs   n_obs        scale
80      math_q11_total_timing  2.514688e+07  923309     1.000000
101  science_q11_total_timing  2.476982e+07  923309     1.000000
100  science_q10_total_timing  1.544223e+07  923309     1.000000
99    science_q9_total_timing  1.091801e+07  923309     1.000000
62    reading_q8_total_timing  6.277968e+06  923309     1.000000
81      math_q12_total_timing  6.041754e+06  923309     1.000000
85      math_q16_total_timing  5.105444e+06  923309     1.000000
84      math_q15_total_timing  3.808254e+06  923309     1.000000
82      math_q13_total_timing  3.661070e+06  923309     1.000000
102  science_q12_total_timing  1.293525e+06  923309     1.000000
63    reading_q9_total_timing  1.225430e+06  923309     1.000000
83      math_q14_total_timing  1.198036e+06  923309     1.000000
64   reading_q10_total_timing  1.679758e+05  923309     1.000000
68   reading_q14_total_timing  1.427232e+05  923309     1.000000
65   reading_q11_total_timing  1.413992e+05  923309     1.000000
66   reading_q12_total_timing  1.403246e+05  923309     1.000000
67   reading_q13_total_timing  8.446880e+04  923309     1.000000
69   reading_q15_total_timing  1.545886e+04  923309     1.000000
61    reading_q7_total_timing  1.271785e+04  923309  1088.493544
79      math_q10_total_timing  7.908642e+03  923309  5567.542808
train |x| p50/p90/p99/max: [0.00000000e+00 2.84366181e+00 2.57178496e+04] 3.1864712e+07
val   |x| p50/p90/p99/max: [0.00000000e+00 2.84803631e+00 2.56884648e+04] 2.4770028e+07
scaler.scale_ min/p1/p5/median: 0.008165882754645248 0.023050189049294414 0.16666666666666666 1.0
                          col       max_abs   n_obs        scale
63    reading_q9_total_timing  3.186471e+07  923310     1.000000
80      math_q11_total_timing  2.514697e+07  923310     1.000000
101  science_q11_total_timing  1.740785e+07  923310     1.000000
100  science_q10_total_timing  1.544217e+07  923310     1.000000
99    science_q9_total_timing  8.283068e+06  923310     1.000000
62    reading_q8_total_timing  6.277928e+06  923310     1.000000
81      math_q12_total_timing  6.041646e+06  923310     1.000000
84      math_q15_total_timing  3.808604e+06  923310     1.000000
82      math_q13_total_timing  3.661091e+06  923310     1.000000
85      math_q16_total_timing  1.743708e+06  923310     1.000000
102  science_q12_total_timing  1.293578e+06  923310     1.000000
83      math_q14_total_timing  1.198062e+06  923310     1.000000
64   reading_q10_total_timing  2.437153e+05  923310     1.000000
68   reading_q14_total_timing  1.492634e+05  923310     1.000000
65   reading_q11_total_timing  1.440851e+05  923310     1.000000
66   reading_q12_total_timing  1.381698e+05  923310     1.000000
67   reading_q13_total_timing  8.091471e+04  923310     1.000000
69   reading_q15_total_timing  1.182729e+04  923310     1.000000
61    reading_q7_total_timing  1.166466e+04  923310  1186.767501
79      math_q10_total_timing  8.140272e+03  923310  5409.125916
train |x| p50/p90/p99/max: [0.00000000e+00 2.85027082e+00 2.56994239e+04] 3.1864808e+07
val   |x| p50/p90/p99/max: [0.00000000e+00 2.85744550e+00 2.57690487e+04] 1.5222783e+07
scaler.scale_ min/p1/p5/median: 0.008580978869879963 0.02273311922149256 0.16666666666666666 1.0
                          col       max_abs   n_obs        scale
63    reading_q9_total_timing  3.186481e+07  923310     1.000000
80      math_q11_total_timing  2.514704e+07  923310     1.000000
101  science_q11_total_timing  2.476976e+07  923310     1.000000
100  science_q10_total_timing  1.544226e+07  923310     1.000000
99    science_q9_total_timing  1.091797e+07  923310     1.000000
85      math_q16_total_timing  5.105660e+06  923310     1.000000
84      math_q15_total_timing  3.808198e+06  923310     1.000000
81      math_q12_total_timing  2.929598e+06  923310     1.000000
82      math_q13_total_timing  2.838374e+06  923310     1.000000
62    reading_q8_total_timing  2.681984e+06  923310     1.000000
83      math_q14_total_timing  1.198089e+06  923310     1.000000
102  science_q12_total_timing  8.817754e+05  923310     1.000000
64   reading_q10_total_timing  2.433758e+05  923310     1.000000
68   reading_q14_total_timing  1.461126e+05  923310     1.000000
66   reading_q12_total_timing  1.423171e+05  923310     1.000000
65   reading_q11_total_timing  9.053750e+04  923310     1.000000
67   reading_q13_total_timing  8.400839e+04  923310     1.000000
69   reading_q15_total_timing  1.545886e+04  923310     1.000000
79      math_q10_total_timing  8.023283e+03  923310  5487.997799
61    reading_q7_total_timing  8.022684e+03  923310  1057.930129
train |x| p50/p90/p99/max: [0.00000000e+00 2.84774499e+00 2.57082465e+04] 3.1864942e+07
val   |x| p50/p90/p99/max: [0.00000000e+00 2.85307381e+00 2.57573741e+04] 4.395103e+06
scaler.scale_ min/p1/p5/median: 0.008552726208313932 0.02246706770950424 0.16666666666666666 1.0
                          col       max_abs   n_obs         scale
63    reading_q9_total_timing  3.186494e+07  923310      1.000000
80      math_q11_total_timing  2.514692e+07  923310      1.000000
101  science_q11_total_timing  2.476986e+07  923310      1.000000
100  science_q10_total_timing  1.544216e+07  923310      1.000000
99    science_q9_total_timing  1.091794e+07  923310      1.000000
62    reading_q8_total_timing  6.277996e+06  923310      1.000000
81      math_q12_total_timing  6.041738e+06  923310      1.000000
85      math_q16_total_timing  5.105574e+06  923310      1.000000
82      math_q13_total_timing  3.661022e+06  923310      1.000000
102  science_q12_total_timing  1.293506e+06  923310      1.000000
83      math_q14_total_timing  1.198121e+06  923310      1.000000
84      math_q15_total_timing  6.387802e+05  923310      1.000000
64   reading_q10_total_timing  2.429379e+05  923310      1.000000
65   reading_q11_total_timing  1.433444e+05  923310      1.000000
68   reading_q14_total_timing  1.387559e+05  923310      1.000000
66   reading_q12_total_timing  1.154221e+05  923310      1.000000
67   reading_q13_total_timing  8.249555e+04  923310      1.000000
61    reading_q7_total_timing  1.268248e+04  923310   1091.527768
79      math_q10_total_timing  7.989407e+03  923310   5511.256697
78       math_q9_total_timing  4.929569e+03  923310  15291.342352

In [14]:
data_raw = X_train_piza.copy()

In [15]:
scaler = RobustScaler()
data_raw = scaler.fit_transform(data_raw).astype(np.float32)

C:\Users\Concordance\PycharmProjects\hickathon-6\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1216: RuntimeWarning: All-NaN slice encountered
  return fnb._ureduce(a, func=_nanmedian, keepdims=keepdims,
C:\Users\Concordance\PycharmProjects\hickathon-6\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1406: RuntimeWarning: All-NaN slice encountered
  return _nanquantile_unchecked(

In [17]:
pd.DataFrame(data_raw).describe()

,0,1,2,3,4,5,6,7,8,9,...,100,101,102,103,104,105,106,107,108,109
count,723431.000000,721429.000000,715079.000000,693857.000000,675195.000000,646352.000000,543316.000000,323908.000000,94392.000000,764.000000,...,330734.000000,222106.000000,45145.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,0.030652,-0.113667,-0.089953,-0.085738,-0.170029,-0.149737,-0.120567,-0.357572,-0.139273,-0.074830,...,0.125827,0.135615,0.059948,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,0.508516,0.506702,0.516234,0.652359,0.644756,0.699140,0.605216,0.679838,0.552958,0.558059,...,1.359312,2.010637,0.986050,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,-0.666667,-0.888889,-1.000000,-1.379310,-1.545455,-1.454545,-1.272727,-1.800000,-1.125000,-1.000000,...,-1.462970,-1.447201,-1.191154,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,-0.333333,-0.555556,-0.500000,-0.413793,-0.545455,-0.454545,-0.522727,-0.800000,-0.625000,-0.500000,...,-0.449670,-0.456242,-0.534658,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,0.666667,0.444444,0.500000,0.586207,0.454545,0.545455,0.477273,0.200000,0.375000,0.500000,...,0.550330,0.543759,0.465342,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,0.666667,0.444444,0.500000,0.689655,0.454545,0.545455,0.477273,0.200000,0.375000,1.000000,...,382.873840,578.693604,38.516476,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
X_train_raw = data_raw.iloc[train_idx]
X_val_raw = data_raw.iloc[val_idx]

imputer = SimpleImputer(strategy="mean", keep_empty_features=True)
X_train_imputed = imputer.fit_transform(X_train_raw)

scaler = RobustScaler()
X_train_scaled = scaler.fit_transform(X_train_imputed).astype(np.float32)

if X_val_raw is not None:
    mask_val = (~np.isnan(X_val_raw)).astype(np.float32)
    X_val_imputed = imputer.transform(X_val_raw)
    X_val_scaled = scaler.transform(X_val_imputed).astype(np.float32)
else:
    val_loader = None

obs_train = X_train_scaled
obs_val = X_val_scaled

In [23]:
pd.DataFrame(X_train_scaled)

,0,1,2,3,4,5,6,7,8,9,...,100,101,102,103,104,105,106,107,108,109
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.681025,1.673577,-2.426349,-0.613198,1.342784,-2.162219,39.973927,0.278759,0.000000,0.0,...,23191.785156,-55067.332031,-41413.199219,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.431025,-2.326423,1.573650,-0.613198,1.584542,-1.032855,39.973927,0.278759,0.343208,0.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-1.568975,-1.326423,1.573650,0.609024,-3.492382,0.507187,-18.486967,-0.221241,0.343208,0.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.431025,0.673577,-0.244531,0.942358,-3.492382,-1.032855,4.897389,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923305,-1.568975,1.673577,0.773651,0.609024,-0.953920,2.355237,39.973927,0.278759,0.343208,0.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
923306,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,-18943.714844,14130.917969,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
923307,-0.068975,-0.326423,1.573650,-0.124309,0.907619,1.709886,10.743480,0.278759,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
923308,1.431025,-1.326423,1.573650,1.831247,1.584542,2.047228,-18.486967,0.028759,0.343208,0.0,...,2041.083008,-24527.082031,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
923309,-0.818975,1.673577,-2.426349,-1.835420,-0.030843,-1.032855,-18.486967,0.278759,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [1]:
import pandas as pd
X_test = pd.read_csv('../data/X_test.csv', sep = ',')
X_test

,Unnamed: 0,Year,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,...,science_q10_total_timing,science_q11_total_timing,science_q12_total_timing,science_q13_total_timing,science_q14_total_timing,science_q15_total_timing,science_q16_total_timing,science_q17_total_timing,science_q18_total_timing,science_q19_total_timing
0,412660,2022,PER,604.0,60400217.0,60404519.0,08MS,60400,PER03,6040000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,554658,2022,ARE,784.0,78400570.0,78413993.0,08MS,78401,ARE41,7840000,...,182597.5,271476.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,937138,2018,JOR,400.0,40000074.0,40001505.0,07MS,40000,JOR9797,4000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,752986,2018,CHL,152.0,15200099.0,15204046.0,07MS,15200,CHL0203,1520000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1084508,2018,PHL,608.0,60800098.0,60801563.0,07MS,60800,PHL0002,6080000,...,11491.5,31846.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586039,1757496,2015,QAR,974.0,97400137.0,97406384.0,06MS,3200,ARG0101,320100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586040,1414197,2015,DEU,276.0,27600225.0,27604959.0,06MS,27600,DEU9797,2760000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586041,821972,2018,ESP,724.0,72400726.0,72420238.0,07MS,72400,ESP9014,7240000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586042,25376,2022,ARG,32.0,3200168.0,3213908.0,08MS,3200,ARG02,320100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586043,722301,2018,CAN,124.0,12400041.0,12422449.0,07MS,12400,CAN0654,1240000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
print(X_test.isna().sum()[(~X_test.isna()).sum() == 0].index)

Index(['math_q1_average_score', 'math_q2_average_score',
       'math_q3_average_score', 'math_q4_average_score',
       'math_q5_average_score', 'math_q6_average_score',
       'math_q7_average_score', 'math_q8_average_score',
       'math_q9_average_score', 'math_q10_average_score',
       'math_q11_average_score', 'math_q12_average_score',
       'math_q13_average_score', 'math_q14_average_score',
       'math_q15_average_score', 'math_q16_average_score',
       'math_q17_average_score', 'math_q18_average_score',
       'math_q19_average_score', 'math_q20_average_score',
       'math_q2_total_timing', 'math_q3_total_timing', 'math_q4_total_timing',
       'math_q5_total_timing', 'math_q6_total_timing', 'math_q7_total_timing',
       'math_q8_total_timing', 'math_q9_total_timing', 'math_q10_total_timing',
       'math_q11_total_timing', 'math_q12_total_timing',
       'math_q13_total_timing', 'math_q14_total_timing',
       'math_q15_total_timing', 'math_q16_total_timing',
       'math_q17_total_timing', 'math_q18_total_timing',
       'math_q19_total_timing', 'math_q20_total_timing',
       'math_q21_total_timing'],
      dtype='object')

In [11]:
import pandas as pd
X_train = pd.read_csv('../data/X_train.csv', sep = ',')
X_test

,Unnamed: 0,Year,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,...,science_q10_total_timing,science_q11_total_timing,science_q12_total_timing,science_q13_total_timing,science_q14_total_timing,science_q15_total_timing,science_q16_total_timing,science_q17_total_timing,science_q18_total_timing,science_q19_total_timing
0,412660,2022,PER,604.0,60400217.0,60404519.0,08MS,60400,PER03,6040000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,554658,2022,ARE,784.0,78400570.0,78413993.0,08MS,78401,ARE41,7840000,...,182597.5,271476.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,937138,2018,JOR,400.0,40000074.0,40001505.0,07MS,40000,JOR9797,4000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,752986,2018,CHL,152.0,15200099.0,15204046.0,07MS,15200,CHL0203,1520000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1084508,2018,PHL,608.0,60800098.0,60801563.0,07MS,60800,PHL0002,6080000,...,11491.5,31846.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586039,1757496,2015,QAR,974.0,97400137.0,97406384.0,06MS,3200,ARG0101,320100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586040,1414197,2015,DEU,276.0,27600225.0,27604959.0,06MS,27600,DEU9797,2760000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586041,821972,2018,ESP,724.0,72400726.0,72420238.0,07MS,72400,ESP9014,7240000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586042,25376,2022,ARG,32.0,3200168.0,3213908.0,08MS,3200,ARG02,320100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586043,722301,2018,CAN,124.0,12400041.0,12422449.0,07MS,12400,CAN0654,1240000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
COLUMNS_TO_LOAD = [
    'WB153', 'ST253', 'ST311', 'WB165', 'IC171', 'ST038', 'IC180', 'ST255', 'ST350', 'ST034',
    'FL162', 'PA195', 'ST330', 'FL169', 'ST230', 'ST331', 'ST354', 'PA042', 'ST305', 'ST258',
    'PA167', 'IC176', 'ST352', 'IC173', 'PA188', 'ST283', 'ST256', 'WB154', 'WB166', 'FL150',
    'ST266', 'IC174', 'ST005', 'ST021', 'IC182', 'FL164', 'FL160', 'ST267', 'ST338', 'ST351',
    'ST342', 'ST355', 'FL166', 'PA183', 'ST007', 'FL170', 'WB168', 'WB163', 'IC184', 'ST348',
    'ST226', 'ST336', 'WB160', 'FL167', 'PA166', 'ST250', 'ST268', 'IC177', 'PA196', 'IC183',
    'ST275', 'IC172', 'IC175', 'ST340', 'ST296', 'ST270', 'ST289', 'ST353', 'ST349', 'ST301',
    'PA186', 'WB164', 'PA197', 'ST290', 'ST062', 'ST254', 'ST345', 'ST322', 'IC170', 'PA006',
    'ST347', 'ST343', 'ST307', 'ST160', 'ST168', 'ST161', 'ST153', 'ST188', 'PA009', 'PA182',
    'PA004', 'ST059', 'ST150', 'PA158', 'WB155', 'WB162', 'ST127', 'EC162', 'ST104', 'PA003',
    'ST125', 'ST163', 'ST297', 'ST006', 'ST263', 'PA162', 'ST164', 'ST008', 'EC031', 'WB177',
    'ST183', 'EC012', 'ST223', 'ST177', 'ST102', 'PA041', 'EC163', 'PA008', 'PA177', 'ST175',
    'ST273', 'EC153', 'ST212', 'PA154', 'PA156', 'PA007', 'PA159', 'ST300', 'ST036', 'PA018',
    'ST208', 'ST165', 'PA175', 'ST167', 'ST211', 'WB176', 'ST158', 'WB178', 'IC014', 'ST213',
    'ST327', 'ST251', 'ST260', 'PA160', 'ST095', 'PA033', 'ST146', 'ST098', 'ST100', 'ST097',
    'ST113', 'PA002', 'PA032', 'IC001',
]

In [12]:
X_train[COLUMNS_TO_LOAD]

,WB153,ST253,ST311,WB165,IC171,ST038,IC180,ST255,ST350,ST034,...,ST095,PA033,ST146,ST098,ST100,ST097,ST113,PA002,PA032,IC001
0,2.5,1.000000,3.25,1.0,0.00,0.000000,0.0,0.666667,0.0,2.333333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,0.0,0.00,0.000000,NaN,0.200000,NaN,2.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,0.0,3.50,0.000000,NaN,0.600000,NaN,2.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.666667,0.000000,0.0,1.000000,0.666667,1.0,1.333333,0.000000,0.0,7.0
4,NaN,NaN,NaN,0.0,0.00,6.000000,NaN,0.200000,NaN,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1172081,0.0,0.857143,0.00,0.0,2.20,0.000000,4.0,0.333333,1.0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1172082,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.333333,3.333333,3.0,3.666667,3.333333,2.0,1.666667,1.333333,0.0,0.0
1172083,0.0,0.857143,3.75,0.0,2.80,0.333333,6.0,0.333333,0.0,3.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1172084,NaN,NaN,NaN,0.0,3.75,1.333333,NaN,0.800000,NaN,3.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1172085,0.0,0.714286,2.50,0.0,0.00,4.333333,0.0,0.000000,0.0,2.333333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
WINSOR_COLUMNS = [
    'WB153', 'ST253', 'WB165', 'ST038', 'ST350', 'ST034', 'FL162', 'PA195', 'FL169', 'PA042',
    'ST305', 'ST258', 'PA167', 'ST352', 'IC173', 'PA188', 'ST256', 'WB154', 'WB166', 'FL150',
    'ST266', 'IC174', 'ST005', 'ST021', 'FL164', 'FL160', 'ST267', 'ST338', 'FL166', 'PA183',
    'ST007', 'FL170', 'WB168', 'WB163', 'IC184', 'WB160', 'FL167', 'PA166', 'IC177', 'PA196',
    'ST275', 'IC175', 'ST296', 'ST353', 'ST349', 'ST301', 'PA186', 'WB164', 'PA197', 'ST062',
    'PA006', 'ST343', 'ST307', 'ST160', 'ST161', 'ST188', 'PA009', 'PA182', 'PA004', 'ST059',
    'PA158', 'WB155', 'WB162', 'ST127', 'EC162', 'PA003', 'ST297', 'ST006', 'PA162', 'ST008',
    'EC031', 'WB177', 'EC012', 'ST223', 'PA041', 'EC163', 'PA008', 'PA177', 'ST273', 'PA154',
    'PA156', 'PA007', 'PA159', 'ST036', 'PA018', 'PA175', 'WB176', 'WB178', 'ST260', 'PA160',
    'PA033', 'ST146', 'PA002', 'PA032',
]

In [15]:
X_test[WINSOR_COLUMNS]

,WB153,ST253,WB165,ST038,ST350,ST034,FL162,PA195,FL169,PA042,...,PA175,WB176,WB178,ST260,PA160,PA033,ST146,PA002,PA032,ST011
0,0.0,0.857143,0.0,0.333333,1.0,1.333333,1.666667,0.0,4.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.857143,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,0.0,0.333333,NaN,3.000000,NaN,NaN,NaN,0.0,...,0.0,0.00,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,0.0,2.000000,NaN,3.000000,NaN,NaN,NaN,0.0,...,0.0,0.00,0.0,0.0,4.0,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,0.0,4.333333,NaN,3.333333,NaN,NaN,NaN,0.0,...,0.0,0.00,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,7.0
586040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,3.0,13.0
586041,NaN,NaN,0.0,0.000000,NaN,3.000000,NaN,NaN,NaN,0.0,...,0.0,0.25,5.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
586042,0.0,0.000000,0.0,0.333333,0.0,2.000000,0.000000,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586043,NaN,NaN,0.0,2.333333,NaN,4.000000,NaN,NaN,NaN,0.0,...,0.0,0.00,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

In [16]:
X_train.shape

(1172086, 307)

In [17]:
for X in WINSOR_COLUMNS:
    print(X, X in COLUMNS_TO_LOAD)

WB153 True
ST253 True
WB165 True
ST038 True
ST350 True
ST034 True
FL162 True
PA195 True
FL169 True
PA042 True
ST305 True
ST258 True
PA167 True
ST352 True
IC173 True
PA188 True
ST256 True
WB154 True
WB166 True
FL150 True
ST266 True
IC174 True
ST005 True
ST021 True
FL164 True
FL160 True
ST267 True
ST338 True
FL166 True
PA183 True
ST007 True
FL170 True
WB168 True
WB163 True
IC184 True
WB160 True
FL167 True
PA166 True
IC177 True
PA196 True
ST275 True
IC175 True
ST296 True
ST353 True
ST349 True
ST301 True
PA186 True
WB164 True
PA197 True
ST062 True
PA006 True
ST343 True
ST307 True
ST160 True
ST161 True
ST188 True
PA009 True
PA182 True
PA004 True
ST059 True
PA158 True
WB155 True
WB162 True
ST127 True
EC162 True
PA003 True
ST297 True
ST006 True
PA162 True
ST008 True
EC031 True
WB177 True
EC012 True
ST223 True
PA041 True
EC163 True
PA008 True
PA177 True
ST273 True
PA154 True
PA156 True
PA007 True
PA159 True
ST036 True
PA018 True
PA175 True
WB176 True
WB178 True
ST260 True
PA160 True
PA033 True
ST146 True
PA002 True
PA032 True
ST011 False

In [18]:
len(COLUMNS_TO_LOAD)

154